[package]
name = "codember"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "challenge01"
src = "2023/Challenge-01/src/main.rs"
path = "2023/Challenge-01/main.rs"

[dependencies]
